/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2022, Outscale SAS
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

 /*
  * This code is autogenerated, don't edit it directely
  */

#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "curl/curl.h"
#include "osc_sdk.h"
#include "json.h"

#define AK_SIZE 20
#define SK_SIZE 40

#ifdef WITH_DESCRIPTION

static const char *calls_name[] = {
	NULL
};

static const char *calls_descriptions[] = {
	NULL
};

static const char *calls_args_descriptions[] = {
	NULL
};

const char *osc_find_description(const char *call_name)
{
	const char **c;
	int i = 0;

	for (c = calls_name; c; ++c) {
		if (!strcmp(*c, call_name))
			return calls_descriptions[i];
		++i;
	}
	return NULL;
}

const char *osc_find_args_description(const char *call_name)
{
	const char **c;
	int i = 0;

	for (c = calls_name; c; ++c) {
		if (!strcmp(*c, call_name))
			return calls_args_descriptions[i];
		++i;
	}
	return NULL;
}

#endif  /* WITH_DESCRIPTION */

static void *osc_realloc(void *buf, size_t l)
{
	void *ret = realloc(buf, l);

	if (!ret)
		free(buf);
	return ret;
}

/* We don't use _Bool as we try to be C89 compatible */
int osc_str_append_bool(struct osc_str *osc_str, int bool)
{
	int len = osc_str->len;
	assert(osc_str);

	osc_str->len = len + (bool ? 4 : 5);
	osc_str->buf = osc_realloc(osc_str->buf, osc_str->len + 1);
	if (!osc_str->buf)
		return -1;
	strcpy(osc_str->buf + len, (bool ? "true" : "false"));
	return 0;
}

int osc_str_append_int(struct osc_str *osc_str, int i)
{
	int len = osc_str->len;
	assert(osc_str);

	osc_str->buf = osc_realloc(osc_str->buf, len + 64);
	if (!osc_str->buf)
		return -1;
	osc_str->len = len + snprintf(osc_str->buf + len, 64, "%d", i);
	osc_str->buf[osc_str->len] = 0;
	return 0;
}

int osc_str_append_double(struct osc_str *osc_str, double i)
{
	int len = osc_str->len;
	assert(osc_str);

	osc_str->buf = osc_realloc(osc_str->buf, len + 64);
	if (!osc_str->buf)
		return -1;
	osc_str->len = len + snprintf(osc_str->buf + len, 64, "%f", i);
	osc_str->buf[osc_str->len] = 0;
	return 0;
}

int osc_str_append_string(struct osc_str *osc_str, const char *str)
{
	if (!str)
		return 0;
	assert(osc_str);

	int len = osc_str->len;
	int dlen = strlen(str);

	osc_str->len = osc_str->len + dlen;
	osc_str->buf = osc_realloc(osc_str->buf, osc_str->len + 1);
	if (!osc_str->buf)
		return -1;
	memcpy(osc_str->buf + len, str, dlen + 1);
	return 0;
}

int osc_load_ak_sk_from_conf(const char *profile, char **ak, char **sk)
{
	const char *dest = "/.osc/config.json";
	char *home = getenv("HOME");
	char buf[1024];
	struct json_object *js;

	*sk = NULL;
	*ak = NULL;
	strcpy(stpcpy(buf, home), dest);
	js = json_object_from_file(buf);
	if (!js) {
		fprintf(stderr, "can't open %s\n", buf);
		return -1;
	}
	js = json_object_object_get(js, profile);
	if (!js) {
		fprintf(stderr, "can't find profile '%s'\n", profile);
		return -1;
	}
	*ak = strdup(json_object_get_string(json_object_object_get(js, "access_key")));
	*sk = strdup(json_object_get_string(json_object_object_get(js, "secret_key")));
	return 0;
}

int osc_load_region_from_conf(const char *profile, char **region)
{
	const char *dest = "/.osc/config.json";
	char *home = getenv("HOME");
	struct json_object *region_obj;
	char buf[1024];
	struct json_object *js;

	strcpy(stpcpy(buf, home), dest);
	js = json_object_from_file(buf);
	if (!js) {
		fprintf(stderr, "can't open %s\n", buf);
		return -1;
	}
	js = json_object_object_get(js, profile);
	if (!js)
		return -1;

	region_obj = json_object_object_get(js, "region");
	if (!region_obj) {
		return -1;
	}
	*region = strdup(json_object_get_string(region_obj));
	return 0;
}

/* Function that will write the data inside a variable */
static size_t write_data(void *data, size_t size, size_t nmemb, void *userp)
{
	size_t bufsize = size * nmemb;
	struct osc_str *response = userp;
	int olen = response->len;

	response->len = response->len + bufsize;
	response->buf = osc_realloc(response->buf, response->len + 1);
	memcpy(response->buf + olen, data, bufsize);
	response->buf[response->len] = 0;
	return bufsize;
}

void osc_init_str(struct osc_str *r)
{
	r->len = 0;
	r->buf = NULL;
}

void osc_deinit_str(struct osc_str *r)
{
	free(r->buf);
	osc_init_str(r);
}



int osc_init_sdk(struct osc_env *e, const char *profile, unsigned int flag)
{
	char ak_sk[AK_SIZE + SK_SIZE + 2];
	char *ca = getenv("CURL_CA_BUNDLE");
	char *endpoint;
	char *env_ak = getenv("OSC_ACCESS_KEY");
	char *env_sk = getenv("OSC_SECRET_KEY");

	e->region = getenv("OSC_REGION");
	e->flag = flag;
	endpoint = getenv("OSC_ENDPOINT_API");
	osc_init_str(&e->endpoint);
	if (!profile) {
		profile = getenv("OSC_PROFILE");
		e->ak = env_ak;
		e->sk = env_sk;
		if (!profile && (!e->ak || !e->sk))
			profile = "default";
	}

	if (profile) {
		if (osc_load_ak_sk_from_conf(profile, &e->ak, &e->sk))
			return -1;
		if (!osc_load_region_from_conf(profile, &e->region))
			e->flag |= OSC_ENV_FREE_REGION;
		e->flag |= OSC_ENV_FREE_AK_SK;
	}

	if (!e->region)
		e->region = "eu-west-2";

	if (!endpoint) {
		osc_str_append_string(&e->endpoint, "https://api.");
		osc_str_append_string(&e->endpoint, e->region);
		osc_str_append_string(&e->endpoint, ".outscale.com");
	} else {
		osc_str_append_string(&e->endpoint, endpoint);
	}

	if (!e->ak || !e->sk) {
		fprintf(stderr, "access key and secret key needed\n");
		return -1;
	}

	if (strlen(e->ak) != AK_SIZE || strlen(e->sk) != SK_SIZE) {
		fprintf(stderr, "Wrong access key or secret key size\n");
		return -1;
	}

	e->headers = NULL;
	stpcpy(stpcpy(stpcpy(ak_sk, e->ak), ":"), e->sk);
	e->c = curl_easy_init();
	e->headers = curl_slist_append(e->headers, "Content-Type: application/json");

	/* Setting HEADERS */
	if (flag & OSC_VERBOSE_MODE)
		curl_easy_setopt(e->c, CURLOPT_VERBOSE, 1);
	if (flag & OSC_INSECURE_MODE)
		curl_easy_setopt(e->c, CURLOPT_SSL_VERIFYPEER, 0);
	curl_easy_setopt(e->c, CURLOPT_HTTPHEADER, e->headers);
	curl_easy_setopt(e->c, CURLOPT_WRITEFUNCTION, write_data);

	/* setting CA is CURL_CA_BUNDLE is set */
	if (ca)
	  curl_easy_setopt(e->c, CURLOPT_CAINFO, ca);

	/* For authentification we specify the method and our acces key / secret key */
	curl_easy_setopt(e->c, CURLOPT_AWS_SIGV4, "osc");
	curl_easy_setopt(e->c, CURLOPT_USERPWD, ak_sk);

	return 0;
}

void osc_deinit_sdk(struct osc_env *e)
{
	curl_slist_free_all(e->headers);
	curl_easy_cleanup(e->c);
	osc_deinit_str(&e->endpoint);
	if (e->flag & OSC_ENV_FREE_AK_SK) {
		free(e->ak);
		e->ak = NULL;
		free(e->sk);
		e->sk = NULL;
	}
	if (e->flag & OSC_ENV_FREE_REGION) {
		free(e->region);
		e->region = NULL;
	}
	e->c = NULL;
	e->flag = 0;
}
