name: Outscale API release
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  oapi-cli:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: master
      - name: Trigger oapi-cli build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: .github/scripts/build-osc-sdk.sh oapi-cli master
